variables:
  REPO_NAME: gitlab.com/paulaolmedo/image-loader
  MONGO_URI: mongodb://mongo

services:
  - mongo

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - lint
  - test

include:
  - template: Code-Quality.gitlab-ci.yml

linting:
  stage: lint
  image: golang:latest
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

test:
  stage: test
  image: golang:latest
  script:
    - go test -race -v -coverpkg ./... ./test/ -coverprofile=cover.out
    - go tool cover -html=cover.out -o coverage.html
  artifacts:
    paths: [coverage.html]

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]