swagger: "2.0"
info:
  title: Satellite Image Loader
  description: Service to interact with satellite images on a database
  version: "1.0"
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /images:
    post:
      tags:
      - Images
      summary: Load new satellite image Images
      description: loads a new image into the database
      operationId: Images#Load new satellite image
      parameters:
      - name: Load New Satellite ImageRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ImagesLoadNewSatelliteImageRequestBody'
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ImagesLoadNewSatelliteImageBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ImagesLoadNewSatelliteImageInternalErrorResponseBody'
      schemes:
      - http
definitions:
  GeographicInformationRequestBody:
    title: GeographicInformationRequestBody
    type: object
    properties:
      coordinates:
        type: object
        description: Coordinates of the satellite image
        example:
          Odit tempore veritatis omnis qui.: 0.06326118638228886
          Praesentium animi.: 0.5249641471441092
        additionalProperties: true
      tag_name:
        type: string
        description: Non-forgetable identifier
        example: Tempore nesciunt aut.
    example:
      coordinates:
        Dolorum et.: 0.17162870836983105
        Eos sit.: 0.1907488332785942
        Incidunt vero accusamus molestiae sed molestias praesentium.: 0.8597346016425331
      tag_name: Exercitationem aut reiciendis.
  ImagesLoadNewSatelliteImageBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Load new satellite image_BadRequest_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ImagesLoadNewSatelliteImageInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Load new satellite image_InternalError_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ImagesLoadNewSatelliteImageRequestBody:
    title: ImagesLoadNewSatelliteImageRequestBody
    type: object
    properties:
      date_time:
        type: string
        description: When was the image taken
        example: "1998-07-04T11:00:59Z"
        format: date-time
      geographic_information:
        $ref: '#/definitions/GeographicInformationRequestBody'
      id:
        type: string
        description: The image identifier
        example: Similique dolores aut.
      normalized_indexes:
        $ref: '#/definitions/NormalizedIndexesRequestBody'
    example:
      date_time: "2011-06-29T10:18:11Z"
      geographic_information:
        coordinates:
          Sit facilis qui et voluptas.: 0.45731705303115716
        tag_name: Nemo occaecati aperiam quis autem.
      id: Cum facere rerum similique.
      normalized_indexes:
        ndvi:
        - 0.18711642837954914
        - 0.09177180070813358
        - 0.7808423638626252
        ndwi:
        - 0.7146847364477503
        - 0.540422727294012
        - 0.5322622263700029
        - 0.299780450041929
  NormalizedIndexesRequestBody:
    title: NormalizedIndexesRequestBody
    type: object
    properties:
      ndvi:
        type: array
        items:
          type: number
          example: 0.22252820316000177
          format: double
        description: Normalized difference vegetation index
        example:
        - 0.7625390703059335
        - 0.23932540533325228
      ndwi:
        type: array
        items:
          type: number
          example: 0.5860649462854428
          format: double
        description: Normalized difference water index
        example:
        - 0.15742692730399646
        - 0.4672100684598644
        - 0.17376185942297107
    example:
      ndvi:
      - 0.05154240802661695
      - 0.11004357756566292
      ndwi:
      - 0.5416604913612656
      - 0.7360220908244918
      - 0.5953897976243496
      - 0.22759491267661675
