version: "3.5"

services:
  mongo:
    image: mongo
    ports:
        - "27017:27017"
    volumes:
        - ./db:/data/db
    networks:
        - localhost
  app:
    image: paulabeatrizolmedo/image-loader
    ports:
      - "8080:8080"
    restart: unless-stopped  
    networks:
      - localhost
 
networks:
  localhost: